title: Potential Total Software Deployment RMM Tool Process Activity
id: 86a70a18-65cd-4cc9-a61f-7da595dbc84d
status: experimental
description: |
    Detects potential processes activity of Total Software Deployment RMM tool
references:
    - https://github.com/magicsword-io/LOLRMM
author: LOLRMM Project
date: 2025-12-01
tags:
    - attack.execution
    - attack.t1219
logsource:
    product: windows
    category: process_creation
detection:
    selection_parent:
        ParentImage|endswith:
            - tniwinagent.exe
            - Tsdservice.exe
    selection_image:
        Image|endswith:
            - tniwinagent.exe
            - Tsdservice.exe
    condition: 1 of selection_*
falsepositives:
    - Legitimate use of Total Software Deployment
level: medium
