Name: Total Software Deployment
Category: 'RMM'
Description: Total Software Deployment is a remote monitoring and management (RMM) tool. More information will be added as it becomes available.
Author: ''
Created: '2024-08-02'
LastModified: '2024-08-02'
Details:
    Website: 'https://www.total-software-deployment.com/'
    PEMetadata:
        Filename: ''
        OriginalFileName: ''
        Description: ''
    Privileges: ''
    Free: ''
    Verification: ''
    SupportedOS: []
    Capabilities: []
    Vulnerabilities: []
    InstallationPaths:
        - C:\ProgramData\Total Software Deployment\*
        - '*\Total Software Deployment\*'
        - '*\tniwinagent.exe'
        - '*\Tsdservice.exe'
Artifacts:
    Disk: []
    EventLog: []
    Registry: []
    Network: []
Detections:
    - Sigma: https://github.com/magicsword-io/LOLRMM/blob/main/detections/sigma/total_software_deployment_processes_sigma.yml
      Description: Detects potential processes activity of Total Software Deployment RMM tool
References: []
Acknowledgement: []
